### ISSUE TITLE
Breaks the debugger.

### ISSUE THREAD

**Issue by ghost** [iwyg/apipage#2]
Adding &debug to the url does not show debugger only a blank page or sometime black page.

**Comment by iwyg** [comment]
Sorry, cannot replicate this. Are you using ContentTypeMappings on the same page?

**Comment by korelogic** [comment]
Nope.

I just get a black page when trying to append ?debug=xml

**Comment by korelogic** [comment]
?debug=params works though.

**Comment by iwyg** [comment]
Can you tell which version of Symphony and Debug Devkit you are using?

**Comment by korelogic** [comment]
Symphony: 2.3.1
Profile Devkit: 1.1
Debug Devkit 1.2.2

**Comment by iwyg** [comment]
But the actual output works as expected?

**Comment by korelogic** [comment]
Yes its just the debugger that is blank.

**Comment by zooshme** [comment]
I can confirm. I seem to have the same issue.

**Comment by iwyg** [comment]
91a97963e614c3a1ac resolves this issue

seems like the debugger is breaking when sending along a content length header. The content length header is now disabled for the debugger view. You may also disable it for all requests in `System->Configuration`.
